# /etc/apache2/sites-available/alcanos.conf
# Requiere: sudo a2enmod proxy proxy_http headers
<VirtualHost *:80>
    ServerName alcanos.sigpri.com
    ProxyPreserveHost On
    ProxyPass        / http://127.0.0.1:3010/
    ProxyPassReverse / http://127.0.0.1:3010/
</VirtualHost>
